/**
 * Enrich catalog JSON files with derived specs from CSV-derived database.
 *
 * Run: node scripts/enrich-catalog.js
 *
 * Reads data-fixtures/catalog_*.json, enriches with spec data from
 * scripts/cpu-specs-database.json (generated by parse-cpu-specs.py),
 * and writes enriched versions to src/data/.
 */

import { readFileSync, writeFileSync, mkdirSync } from 'fs'
import { join, dirname } from 'path'
import { fileURLToPath } from 'url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = join(__dirname, '..')
const FIXTURES = join(ROOT, 'data-fixtures')
const DATA = join(ROOT, 'src', 'data')
const SPECS_DB = join(ROOT, 'scripts', 'cpu-specs-database.json')

// ═══════════════════════════════════════════════════════════════════════════
// Load CPU specifications database
// ═══════════════════════════════════════════════════════════════════════════

let cpuSpecsDb = null

function loadCpuSpecsDb() {
  try {
    const raw = readFileSync(SPECS_DB, 'utf-8')
    cpuSpecsDb = JSON.parse(raw)
    console.log(`  Loaded CPU specs database: ${cpuSpecsDb.amd.length} AMD, ${cpuSpecsDb.intel.length} Intel entries`)
  } catch (e) {
    console.warn('  ⚠ Could not load CPU specs database, falling back to heuristic-only enrichment')
    console.warn(`    ${e.message}`)
    cpuSpecsDb = null
  }
}

/**
 * Find matching CPU spec entry from the database.
 * Uses a scoring system: longer/more-specific key matches score higher.
 */
function findCpuSpec(name, brand) {
  if (!cpuSpecsDb) return null

  const nameLower = name.toLowerCase().replace(/[™®]/g, '')
  const entries = brand === 'Intel' ? cpuSpecsDb.intel : cpuSpecsDb.amd

  let bestMatch = null
  let bestScore = 0

  for (const entry of entries) {
    for (const key of entry.modelKeys) {
      const keyLower = key.toLowerCase()
      // Use word boundary matching to avoid partial matches like "7700" matching "77000"
      // But also allow embedded matches like "5600x" in "Ryzen 5 5600X"
      if (nameLower.includes(keyLower)) {
        // Score: prefer longer keys (more specific matches) and full-name keys
        let score = keyLower.length
        if (keyLower.startsWith('ryzen ') || keyLower.startsWith('core ')) score += 20
        if (keyLower.startsWith('i') && keyLower.includes('-')) score += 15 // i5-14600k style
        // Prefer exact model number match
        if (new RegExp(`\\b${escapeRegex(keyLower)}\\b`, 'i').test(nameLower)) score += 5
        if (score > bestScore) {
          bestScore = score
          bestMatch = entry
        }
      }
    }
  }
  return bestMatch
}

function escapeRegex(str) {
  return str.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
}

// ═══════════════════════════════════════════════════════════════════════════
// CPU spec enrichment (CSV database + heuristic fallback)
// ═══════════════════════════════════════════════════════════════════════════

// Heuristic fallback for CPUs not found in the database
const AMD_CPU_SPECS_FALLBACK = {
  '3200G':  { socket: 'AM4', cores: '4', threads: '4',  tdp: '65W' },
  '4600G':  { socket: 'AM4', cores: '6', threads: '12', tdp: '65W' },
  '5500GT': { socket: 'AM4', cores: '6', threads: '12', tdp: '65W' },
  '5600G':  { socket: 'AM4', cores: '6', threads: '12', tdp: '65W' },
  '5600GT': { socket: 'AM4', cores: '6', threads: '12', tdp: '65W' },
  '5600X':  { socket: 'AM4', cores: '6', threads: '12', tdp: '65W' },
  '5700G':  { socket: 'AM4', cores: '8', threads: '16', tdp: '65W' },
  '5700X':  { socket: 'AM4', cores: '8', threads: '16', tdp: '65W' },
  '8500G':  { socket: 'AM5', cores: '6', threads: '12', tdp: '65W' },
  '8600G':  { socket: 'AM5', cores: '6', threads: '12', tdp: '65W' },
  '7600':   { socket: 'AM5', cores: '6', threads: '12', tdp: '65W' },
  '7600X':  { socket: 'AM5', cores: '6', threads: '12', tdp: '105W' },
  '9600X':  { socket: 'AM5', cores: '6', threads: '12', tdp: '65W' },
  '7700':   { socket: 'AM5', cores: '8', threads: '16', tdp: '65W' },
  '7700X':  { socket: 'AM5', cores: '8', threads: '16', tdp: '105W' },
  '8700G':  { socket: 'AM5', cores: '8', threads: '16', tdp: '65W' },
  '7800X3D': { socket: 'AM5', cores: '8', threads: '16', tdp: '120W' },
  '9800X3D': { socket: 'AM5', cores: '8', threads: '16', tdp: '120W' },
  '9850X3D': { socket: 'AM5', cores: '8', threads: '16', tdp: '120W' },
  '9900X':  { socket: 'AM5', cores: '12', threads: '24', tdp: '120W' },
  '9900X3D': { socket: 'AM5', cores: '12', threads: '24', tdp: '120W' },
  '9950X':  { socket: 'AM5', cores: '16', threads: '32', tdp: '170W' },
  '9950X3D': { socket: 'AM5', cores: '16', threads: '32', tdp: '170W' },
  '9700X':  { socket: 'AM5', cores: '8', threads: '16', tdp: '65W' },
  '9600':   { socket: 'AM5', cores: '6', threads: '12', tdp: '65W' },
  '7500F':  { socket: 'AM5', cores: '6', threads: '12', tdp: '65W' },
  '7500':   { socket: 'AM5', cores: '6', threads: '12', tdp: '65W' },
  '7700X3D': { socket: 'AM5', cores: '8', threads: '16', tdp: '120W' },
  '3000G':  { socket: 'AM4', cores: '4', threads: '4',  tdp: '35W' },
}

/**
 * Human-friendly label mapping for spec keys
 * Keys not in this map will be shown in UPPERCASE as before
 */
const SPEC_LABELS = {
  brand: 'Brand',
  sku: 'SKU',
  availability: 'Availability',
  socket: 'Socket',
  cores: 'Cores',
  threads: 'Threads',
  pCores: 'P-Cores',
  eCores: 'E-Cores',
  tdp: 'TDP',
  baseClock: 'Base Clock',
  boostClock: 'Boost Clock',
  pCoreBaseClock: 'P-Core Base',
  eCoreBaseClock: 'E-Core Base',
  cache: 'Cache',
  l2Cache: 'L2 Cache',
  l3Cache: 'L3 Cache',
  memoryType: 'Memory Type',
  memoryChannels: 'Memory Channels',
  maxMemory: 'Max Memory',
  pcieVersion: 'PCIe Version',
  pcieLanes: 'PCIe Lanes',
  integratedGraphics: 'Integrated GPU',
  graphicsCoreCount: 'GPU Cores',
  graphicsMaxFreq: 'GPU Max Freq',
  configurableTdp: 'Configurable TDP',
  unlocked: 'Unlocked',
  maxTemp: 'Max Temp',
  generation: 'Generation',
  yearLaunched: 'Year',
  brandType: 'Brand',
  series: 'Series',
  brandLevel: 'Tier',
  turboBoostMax: 'Turbo Boost Max',
  vPro: 'vPro',
  ram: 'Memory',
  ram_type: 'Memory',
  vram: 'VRAM',
}

/**
 * Order in which to display CPU specs (missing keys are appended at end)
 */
const CPU_SPEC_ORDER = [
  'brand', 'socket', 'cores', 'pCores', 'eCores', 'threads',
  'baseClock', 'boostClock', 'pCoreBaseClock', 'eCoreBaseClock',
  'cache', 'l2Cache', 'l3Cache', 'tdp', 'configurableTdp',
  'memoryType', 'memoryChannels', 'maxMemory', 'pcieVersion', 'pcieLanes',
  'integratedGraphics', 'graphicsCoreCount', 'graphicsMaxFreq',
  'unlocked', 'maxTemp', 'generation', 'yearLaunched', 'series',
  'turboBoostMax', 'vPro',
  // Legacy/fallback keys
  'brandType', 'brandLevel',
  'sku', 'availability',
]

/**
 * Order specs according to CPU_SPEC_ORDER and rename keys using SPEC_LABELS
 */
function orderAndLabelCpuSpecs(specs) {
  const ordered = {}
  const seenKeys = new Set()

  // First, output keys in preferred order
  for (const key of CPU_SPEC_ORDER) {
    if (specs[key] !== undefined && specs[key] !== '') {
      const label = SPEC_LABELS[key] || key.toUpperCase()
      ordered[label] = specs[key]
      seenKeys.add(key)
    }
  }

  // Then, output any remaining keys
  for (const [key, value] of Object.entries(specs)) {
    if (!seenKeys.has(key) && value !== undefined && value !== '') {
      const label = SPEC_LABELS[key] || key.toUpperCase()
      ordered[label] = value
    }
  }

  return ordered
}

function enrichCpu(item) {
  const name = item.name.replace(/[™®]/g, '')
  const existing = item.specs
  const brand = existing.brand || (/AMD/i.test(name) ? 'AMD' : 'Intel')

  // ── Try CSV database first ──
  const dbMatch = findCpuSpec(name, brand)
  if (dbMatch) {
    // Merge: prefer CSV data, keep existing fields that CSV doesn't cover
    const merged = {
      ...existing,
      ...dbMatch.specs,
    }
    // Ensure brand is preserved correctly
    merged.brand = existing.brand || brand

    // Order and label specs nicely
    const labeled = orderAndLabelCpuSpecs(merged)

    return { ...item, specs: labeled }
  }

  // ── Fall back to heuristic enrichment ──
  if (existing.socket) {
    // Already has some specs, just label them
    const labeled = orderAndLabelCpuSpecs(existing)
    return { ...item, specs: labeled }
  }

  // AMD heuristic fallback
  if (/AMD/i.test(name)) {
    for (const [model, specs] of Object.entries(AMD_CPU_SPECS_FALLBACK)) {
      const pattern = new RegExp(`\\b${model.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\b`)
      if (pattern.test(name)) {
        const merged = { ...existing, ...specs }
        merged.brand = existing.brand || 'AMD'
        return { ...item, specs: orderAndLabelCpuSpecs(merged) }
      }
    }

    // Socket heuristic
    const modelMatch = name.match(/Ryzen\s+\d+\s+(\d{4,5})/i)
    if (modelMatch) {
      const modelNum = parseInt(modelMatch[1])
      return { ...item, specs: orderAndLabelCpuSpecs({ ...existing, brand: existing.brand || 'AMD', socket: modelNum >= 7000 ? 'AM5' : 'AM4' }) }
    }
  }

  // Intel heuristic fallback
  if (/Intel/i.test(name)) {
    // Core Ultra 200 series = LGA 1851
    if (/Ultra/i.test(name) && /2\d{2}[KF]*/i.test(name)) {
      const modelMatch = name.match(/Ultra\s+\d+\s+(\d{3})/i)
      const modelNum = modelMatch ? parseInt(modelMatch[1]) : 0
      const coresMap = { 225: '6', 245: '6', 265: '8', 285: '8' }
      return {
        ...item,
        specs: orderAndLabelCpuSpecs({
          ...existing,
          brand: existing.brand || 'Intel',
          socket: 'LGA1851',
          cores: coresMap[modelNum] || '',
          threads: '',
          tdp: modelNum >= 265 ? '125W' : '65W',
        }),
      }
    }

    // Core i series
    const genMatch = name.match(/i[3579][\s-](\d{4,5})/i)
    if (genMatch) {
      const modelNum = genMatch[1]
      const gen = modelNum.length >= 5 ? parseInt(modelNum.substring(0, 2)) : parseInt(modelNum.substring(0, 2))
      const socket = gen >= 12 ? 'LGA1700' : gen >= 10 ? 'LGA1200' : 'LGA1151'
      const isK = /K[F]?\b/i.test(name)
      const tier = name.match(/i([3579])/i)?.[1]
      const coresMap = {
        '3': { '12': '4', '13': '4', '14': '4', '10': '4', '9': '4' },
        '5': { '12': '6', '13': '10', '14': '10', '10': '6', '9': '6' },
        '7': { '12': '12', '13': '16', '14': '20', '10': '8', '9': '8' },
        '9': { '12': '16', '13': '24', '14': '24', '10': '8', '9': '8' },
      }
      const cores = coresMap?.[tier]?.[String(gen)] || ''

      return {
        ...item,
        specs: orderAndLabelCpuSpecs({ ...existing, brand: existing.brand || 'Intel', socket, cores, threads: '', tdp: isK ? '125W' : '65W' }),
      }
    }

    // Fallback Intel — try LGA from name
    const lgaMatch = name.match(/(?:LGA|Socket)\s*(\d+)/i)
    if (lgaMatch) {
      return { ...item, specs: orderAndLabelCpuSpecs({ ...existing, brand: existing.brand || 'Intel', socket: `LGA${lgaMatch[1]}` }) }
    }
  }

  // Final fallback: try to find socket from any name pattern
  const amdSocketMatch = name.match(/\b(AM[45])\b/i)
  if (amdSocketMatch) {
    return { ...item, specs: orderAndLabelCpuSpecs({ ...existing, brand: existing.brand || 'AMD', socket: amdSocketMatch[1].toUpperCase() }) }
  }
  const lgaSocketMatch = name.match(/(?:LGA|Socket)\s*(\d{3,4})\b/i)
  if (lgaSocketMatch) {
    return { ...item, specs: orderAndLabelCpuSpecs({ ...existing, brand: existing.brand || 'Intel', socket: `LGA${lgaSocketMatch[1]}` }) }
  }

  // Nothing found — just label existing specs
  return { ...item, specs: orderAndLabelCpuSpecs(existing) }
}

// ═══════════════════════════════════════════════════════════════════════════
// Motherboard spec extraction
// ═══════════════════════════════════════════════════════════════════════════

const CHIPSET_MAP = {
  // AMD AM4
  'A320': { socket: 'AM4', ram: 'DDR4' },
  'B350': { socket: 'AM4', ram: 'DDR4' },
  'B450': { socket: 'AM4', ram: 'DDR4' },
  'B550': { socket: 'AM4', ram: 'DDR4' },
  'X370': { socket: 'AM4', ram: 'DDR4' },
  'X470': { socket: 'AM4', ram: 'DDR4' },
  'X570': { socket: 'AM4', ram: 'DDR4' },
  'A520': { socket: 'AM4', ram: 'DDR4' },
  // AMD AM5
  'A620': { socket: 'AM5', ram: 'DDR5' },
  'B650': { socket: 'AM5', ram: 'DDR5' },
  'X670': { socket: 'AM5', ram: 'DDR5' },
  'X870': { socket: 'AM5', ram: 'DDR5' },
  'B840': { socket: 'AM5', ram: 'DDR5' },
  'B850': { socket: 'AM5', ram: 'DDR5' },
  // Intel LGA 1200
  'H410': { socket: 'LGA1200', ram: 'DDR4' },
  'H470': { socket: 'LGA1200', ram: 'DDR4' },
  'B460': { socket: 'LGA1200', ram: 'DDR4' },
  'Z490': { socket: 'LGA1200', ram: 'DDR4' },
  'B560': { socket: 'LGA1200', ram: 'DDR4' },
  'H510': { socket: 'LGA1200', ram: 'DDR4' },
  'H570': { socket: 'LGA1200', ram: 'DDR4' },
  'Z590': { socket: 'LGA1200', ram: 'DDR4' },
  // Intel LGA 1151
  'H310': { socket: 'LGA1151', ram: 'DDR4' },
  'H370': { socket: 'LGA1151', ram: 'DDR4' },
  'B360': { socket: 'LGA1151', ram: 'DDR4' },
  'B365': { socket: 'LGA1151', ram: 'DDR4' },
  'Z390': { socket: 'LGA1151', ram: 'DDR4' },
  'Z370': { socket: 'LGA1151', ram: 'DDR4' },
  // Intel LGA 1700
  'H610': { socket: 'LGA1700', ram: 'DDR4' },
  'B660': { socket: 'LGA1700', ram: 'DDR4' },
  'H670': { socket: 'LGA1700', ram: 'DDR4' },
  'Z690': { socket: 'LGA1700', ram: 'DDR5' },
  'B760': { socket: 'LGA1700', ram: 'DDR5' },
  'H770': { socket: 'LGA1700', ram: 'DDR5' },
  'Z790': { socket: 'LGA1700', ram: 'DDR5' },
  // Intel LGA 1851
  'H810': { socket: 'LGA1851', ram: 'DDR5' },
  'B860': { socket: 'LGA1851', ram: 'DDR5' },
  'Z890': { socket: 'LGA1851', ram: 'DDR5' },
  'H870': { socket: 'LGA1851', ram: 'DDR5' },
}

function enrichMotherboard(item) {
  const name = item.name
  const existing = item.specs

  if (existing.socket) return item

  // Check for explicit DDR hint in name (D4, D5)
  const ddrHint = /D5\b/i.test(name) ? 'DDR5' : /D4\b/i.test(name) ? 'DDR4' : null

  // Extract chipset from name
  // Sort chipsets longest-first so X670E matches before X670
  const sortedChipsets = Object.entries(CHIPSET_MAP).sort((a, b) => b[0].length - a[0].length)

  for (const [chipset, info] of sortedChipsets) {
    // Match chipset with optional trailing letters (e.g., "B450" matches "B450M-HDV")
    const pattern = new RegExp(`\\b${chipset}[A-Z]*\\b`, 'i')
    if (pattern.test(name)) {
      const ram = ddrHint || info.ram
      return {
        ...item,
        specs: { ...existing, socket: info.socket, ram, chipset },
      }
    }
  }

  return item
}

// ═══════════════════════════════════════════════════════════════════════════
// GPU spec extraction (minimal — VRAM from name)
// ═══════════════════════════════════════════════════════════════════════════

function enrichGpu(item) {
  const name = item.name
  const existing = item.specs

  if (existing.vram) return item

  const vramMatch = name.match(/(\d+)\s*GB/i)
  const vram = vramMatch ? vramMatch[1] : ''

  return { ...item, specs: { ...existing, vram } }
}

// ═══════════════════════════════════════════════════════════════════════════
// Main
// ═══════════════════════════════════════════════════════════════════════════

console.log('Enriching catalog files...\n')

// Load CPU specs database
loadCpuSpecsDb()

function processFile(filename, enrichFn) {
  const src = join(FIXTURES, filename)
  const raw = JSON.parse(readFileSync(src, 'utf-8'))
  const enriched = {
    ...raw,
    items: raw.items.map(enrichFn),
  }

  // Stats
  const total = enriched.items.length
  const withSpecs = enriched.items.filter(i => {
    if (filename === 'catalog_cpu.json') {
      return i.specs.Socket || i.specs.socket || i.specs.Cores || i.specs.cores || i.specs.TDP || i.specs.tdp
    }
    if (filename === 'catalog_motherboard.json') {
      return i.specs.socket || i.specs.Socket
    }
    return true
  }).length
  console.log(`${filename}: ${total} items, ${withSpecs} enriched`)

  if (filename === 'catalog_cpu.json') {
    const unmatched = enriched.items.filter(i => !i.specs.Socket && !i.specs.socket && !i.specs.Cores && !i.specs.cores && !i.specs.TDP && !i.specs.tdp)
    if (unmatched.length > 0) {
      console.log(`  ${unmatched.length} CPUs without specs from database:`)
      for (const u of unmatched.slice(0, 5)) {
        console.log(`    - ${u.name}`)
      }
    }
  }

  // Write to src/data/
  mkdirSync(DATA, { recursive: true })
  const dest = join(DATA, filename)
  writeFileSync(dest, JSON.stringify(enriched, null, 2) + '\n')
  console.log(`  → ${dest}`)
}

processFile('catalog_cpu.json', enrichCpu)
processFile('catalog_motherboard.json', enrichMotherboard)
processFile('catalog_gpu.json', enrichGpu)
console.log('\nDone.')